### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by zigreth** [gvilarino/docker-workshop#9]
Hola disculpa consultar por este medio pero no he podido encontrar una respuesta y quisiera saber si me puedes ayudar, el asunto es el siguiente:

vi el curso que tienes en Platzi sobre Docker, pero me surgio una duda con respecto a programar, como lo puedes hacer si por ejemplo un proyecto en java usando eclipse cuando usas librerias debes tenerlas en la carpeta raiz del proyecto ademas de llevarlas a la carpeta de un contenedor, eso se debe hacer asi o existe una manera mas adecuada de trabajar en casos como esos?

de ante mano, muchas gracias.

**Comment by gvilarino** [comment]
Hola! Idealmente, las dependencias deberían ser parte de la configuración de la imagen que usás para trabajar. Para compartir archivos entre el sistema de archivos de tu computadora y el de un contenedor existe toda la funcionalidad de bind mounting.

**Comment by gvilarino** [comment]
(Pasando al inglés):

In any case, Eclipse is an IDE that was designed decades before Docker came along, and I'm not an Eclipse user; I can't really be taken as a good source of advice on how to work with Docker and Eclipse. This guide is meant for understanding how docker works and should be used under the assumption that you code is based on text files and that there's a linux-compatible dependency management framework.

I'm closing this.
